wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700826690.424337
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.9.6
      5: 0.16.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
